**Task 1: Scalar & Array Operations**

In [44]:
import numpy as np

In [45]:
scalar = 3.7
print("Scalar =", scalar)

Scalar = 3.7


In [46]:
arr = np.array([1.2, 2.5, 3.7, 4.1, 5.8, 6.3])

print("Array =", arr)

Array = [1.2 2.5 3.7 4.1 5.8 6.3]


In [47]:
print("sin =", np.sin(arr))
print("cos =", np.cos(arr))
print("tan =", np.tan(arr))

print("Exponential =", np.exp(arr))
print("Logarithm =", np.log(arr))

print("Absolute =", np.abs(arr))
print("Square Root =", np.sqrt(arr))

sin = [ 0.93203909  0.59847214 -0.52983614 -0.81827711 -0.46460218  0.0168139 ]
cos = [ 0.36235775 -0.80114362 -0.84810003 -0.57482395  0.88551952  0.99985864]
tan = [ 2.57215162 -0.7470223   0.62473308  1.42352648 -0.52466622  0.01681628]
Exponential = [  3.32011692  12.18249396  40.44730436  60.3402876  330.29955991
 544.57191013]
Logarithm = [0.18232156 0.91629073 1.30833282 1.41098697 1.75785792 1.84054963]
Absolute = [1.2 2.5 3.7 4.1 5.8 6.3]
Square Root = [1.09544512 1.58113883 1.92353841 2.02484567 2.40831892 2.50998008]


**Task 2: 3×2 Matrix Operations**

In [48]:
matrix = np.array([
    [0.5, 1.2],
    [2.0, 2.5],
    [0.8, 1.5]
])

print("3x2 Matrix:")
print(matrix)

3x2 Matrix:
[[0.5 1.2]
 [2.  2.5]
 [0.8 1.5]]


In [49]:
print("Sin:")
print(np.sin(matrix))

print("Cos:")
print(np.cos(matrix))

print("Tan:")
print(np.tan(matrix))

Sin:
[[0.47942554 0.93203909]
 [0.90929743 0.59847214]
 [0.71735609 0.99749499]]
Cos:
[[ 0.87758256  0.36235775]
 [-0.41614684 -0.80114362]
 [ 0.69670671  0.0707372 ]]
Tan:
[[ 0.54630249  2.57215162]
 [-2.18503986 -0.7470223 ]
 [ 1.02963856 14.10141995]]


In [50]:
print("Exponential:")
print(np.exp(matrix))

Exponential:
[[ 1.64872127  3.32011692]
 [ 7.3890561  12.18249396]
 [ 2.22554093  4.48168907]]


In [51]:
print("Natural Log:")
print(np.log(matrix))

print("Log base 10:")
print(np.log10(matrix))

Natural Log:
[[-0.69314718  0.18232156]
 [ 0.69314718  0.91629073]
 [-0.22314355  0.40546511]]
Log base 10:
[[-0.30103     0.07918125]
 [ 0.30103     0.39794001]
 [-0.09691001  0.17609126]]


In [52]:
print("Absolute Value:")
print(np.abs(matrix))

Absolute Value:
[[0.5 1.2]
 [2.  2.5]
 [0.8 1.5]]


In [53]:
print("Square Root:")
print(np.sqrt(matrix))

Square Root:
[[0.70710678 1.09544512]
 [1.41421356 1.58113883]
 [0.89442719 1.22474487]]


In [54]:
print("Remainder when divided by 2:")
print(np.remainder(matrix, 2))

Remainder when divided by 2:
[[0.5 1.2]
 [0.  0.5]
 [0.8 1.5]]


In [55]:
print("Round:")
print(np.round(matrix))

print("Floor:")
print(np.floor(matrix))

print("Ceil:")
print(np.ceil(matrix))

Round:
[[0. 1.]
 [2. 2.]
 [1. 2.]]
Floor:
[[0. 1.]
 [2. 2.]
 [0. 1.]]
Ceil:
[[1. 2.]
 [2. 3.]
 [1. 2.]]


In [56]:
safe_matrix = np.clip(matrix, -1, 1)

print("Arcsin:")
print(np.arcsin(safe_matrix))

print("Arccos:")
print(np.arccos(safe_matrix))

Arcsin:
[[0.52359878 1.57079633]
 [1.57079633 1.57079633]
 [0.92729522 1.57079633]]
Arccos:
[[1.04719755 0.        ]
 [0.         0.        ]
 [0.64350111 0.        ]]


**Task 4: Vector Functions**

In [57]:
matrix2 = np.array([
    [2.1, 4.7, 1.5],
    [3.8, 6.2, 2.9]
])

print("2x3 Matrix:")
print(matrix2)

2x3 Matrix:
[[2.1 4.7 1.5]
 [3.8 6.2 2.9]]


In [58]:
print("Maximum value:", np.max(matrix2))
print("Minimum value:", np.min(matrix2))
print("Maximum index:", np.argmax(matrix2))
print("Minimum index:", np.argmin(matrix2))
print("Vector length:", np.linalg.norm(matrix2))

Maximum value: 6.2
Minimum value: 1.5
Maximum index: 4
Minimum index: 2
Vector length: 9.488940931421167


In [59]:
sorted_rows = np.sort(matrix2, axis=1)

print("Row-wise ascending:")
print(sorted_rows)
print("Row-wise descending:")
print(np.sort(matrix2, axis=1)[:, ::-1])

Row-wise ascending:
[[1.5 2.1 4.7]
 [2.9 3.8 6.2]]
Row-wise descending:
[[4.7 2.1 1.5]
 [6.2 3.8 2.9]]


In [60]:
flattened = matrix2.flatten()

print("Flattened:")
print(flattened)
print("Entire matrix descending:")
print(np.sort(flattened)[::-1])

Flattened:
[2.1 4.7 1.5 3.8 6.2 2.9]
Entire matrix descending:
[6.2 4.7 3.8 2.9 2.1 1.5]


In [61]:
print("Sum:", np.sum(matrix2))
print("Product:", np.prod(matrix2))
print("Median:", np.median(matrix2))
print("Mean:", np.mean(matrix2))
print("Standard Deviation:", np.std(matrix2))

Sum: 21.2
Product: 1011.53682
Median: 3.3499999999999996
Mean: 3.533333333333333
Standard Deviation: 1.5881505666095461
