In [42]:
import numpy as np

**1. Advanced Scalar &amp; Array Operations**

In [43]:

scalar = 4.3

array = np.array([1.2, -2.5, 3.7, 4.1, -5.3, 6.8, 7.4, -8.2])

print("Scalar:", scalar)
print("Array:", array)

Scalar: 4.3
Array: [ 1.2 -2.5  3.7  4.1 -5.3  6.8  7.4 -8.2]


In [44]:

print("Add:", array + scalar)
print("Sub:", array - scalar)
print("Mul:", array * scalar)
print("Div:", array / scalar)

Add: [ 5.5  1.8  8.   8.4 -1.  11.1 11.7 -3.9]
Sub: [ -3.1  -6.8  -0.6  -0.2  -9.6   2.5   3.1 -12.5]
Mul: [  5.16 -10.75  15.91  17.63 -22.79  29.24  31.82 -35.26]
Div: [ 0.27906977 -0.58139535  0.86046512  0.95348837 -1.23255814  1.58139535
  1.72093023 -1.90697674]


In [45]:
print("Abs Value:",np.abs(array))
print("Square Root:",np.sqrt(np.abs(array)))
print("Exponential:",np.exp(array))
print("Natural Log:",np.log(np.abs(array)))
print("Log Base 10:",np.log10(np.abs(array)))

Abs Value: [1.2 2.5 3.7 4.1 5.3 6.8 7.4 8.2]
Square Root: [1.09544512 1.58113883 1.92353841 2.02484567 2.30217289 2.60768096
 2.7202941  2.86356421]
Exponential: [3.32011692e+00 8.20849986e-02 4.04473044e+01 6.03402876e+01
 4.99159391e-03 8.97847292e+02 1.63598443e+03 2.74653570e-04]
Natural Log: [0.18232156 0.91629073 1.30833282 1.41098697 1.66770682 1.91692261
 2.00148    2.10413415]
Log Base 10: [0.07918125 0.39794001 0.56820172 0.61278386 0.72427587 0.83250891
 0.86923172 0.91381385]


In [46]:
print("Sin: ",np.sin(array))
print("cos: ",np.cos(array))
print("tan: ",np.tan(array))

Sin:  [ 0.93203909 -0.59847214 -0.52983614 -0.81827711  0.83226744  0.49411335
  0.8987081  -0.94073056]
cos:  [ 0.36235775 -0.80114362 -0.84810003 -0.57482395  0.55437434  0.86939749
  0.43854733 -0.33915486]
tan:  [2.57215162 0.7470223  0.62473308 1.42352648 1.5012734  0.56833998
 2.04928417 2.7737493 ]


In [47]:
clipped_array = np.clip(array, -1, 1)

print("Clipped Array:",clipped_array)
print("\narcsin:",np.arcsin(clipped_array))
print("\narccos:",np.arccos(clipped_array))
print("\narctan:",np.arctan(array))


Clipped Array: [ 1. -1.  1.  1. -1.  1.  1. -1.]

arcsin: [ 1.57079633 -1.57079633  1.57079633  1.57079633 -1.57079633  1.57079633
  1.57079633 -1.57079633]

arccos: [0.         3.14159265 0.         0.         3.14159265 0.
 0.         3.14159265]

arctan: [ 0.87605805 -1.19028995  1.3068326   1.33156473 -1.38430943  1.42478407
  1.43647488 -1.44944433]


**2. Matrix Mathematical Operations**

In [48]:
matrix = np.array([
    [1.5, -2.3, 3.7],
    [-4.2, 5.6, -6.1],
    [7.4, -8.5, 9.2],
    [-3.3, 2.8, -1.7]
])

print("4x3 Matrix:",matrix)

4x3 Matrix: [[ 1.5 -2.3  3.7]
 [-4.2  5.6 -6.1]
 [ 7.4 -8.5  9.2]
 [-3.3  2.8 -1.7]]


In [49]:
print("sin:",np.sin(matrix))
print("cos:",np.cos(matrix))
print("\ntan:",np.tan(matrix))

sin: [[ 0.99749499 -0.74570521 -0.52983614]
 [ 0.87157577 -0.63126664  0.1821625 ]
 [ 0.8987081  -0.79848711  0.22288991]
 [ 0.15774569  0.33498815 -0.99166481]]
cos: [[ 0.0707372  -0.66627602 -0.84810003]
 [-0.49026082  0.77556588  0.98326844]
 [ 0.43854733 -0.6020119  -0.97484362]
 [-0.98747977 -0.94222234 -0.12884449]]

tan: [[14.10141995  1.11921364  0.62473308]
 [-1.77777977 -0.81394328  0.18526223]
 [ 2.04928417  1.32636433 -0.22864171]
 [-0.15974575 -0.35552983  7.69660214]]


In [50]:
clipped_matrix = np.clip(matrix, -1, 1)

print("arcsin:",np.arcsin(clipped_matrix))
print("\narccos:",np.arccos(clipped_matrix))
print("\narctan:",np.arctan(matrix))


arcsin: [[ 1.57079633 -1.57079633  1.57079633]
 [-1.57079633  1.57079633 -1.57079633]
 [ 1.57079633 -1.57079633  1.57079633]
 [-1.57079633  1.57079633 -1.57079633]]

arccos: [[0.         3.14159265 0.        ]
 [3.14159265 0.         3.14159265]
 [0.         3.14159265 0.        ]
 [3.14159265 0.         3.14159265]]

arctan: [[ 0.98279372 -1.16066899  1.3068326 ]
 [-1.33705315  1.39408747 -1.40830722]
 [ 1.43647488 -1.45368758  1.46252574]
 [-1.27656176  1.22777239 -1.03907226]]


In [51]:
print("Exponential:",np.exp(matrix))
print("Natural Log:",np.log(np.abs(matrix)))
print("Log Base 10:",np.log10(np.abs(matrix)))

Exponential: [[4.48168907e+00 1.00258844e-01 4.04473044e+01]
 [1.49955768e-02 2.70426407e+02 2.24286772e-03]
 [1.63598443e+03 2.03468369e-04 9.89712906e+03]
 [3.68831674e-02 1.64446468e+01 1.82683524e-01]]
Natural Log: [[0.40546511 0.83290912 1.30833282]
 [1.43508453 1.7227666  1.80828877]
 [2.00148    2.14006616 2.21920348]
 [1.19392247 1.02961942 0.53062825]]
Log Base 10: [[0.17609126 0.36172784 0.56820172]
 [0.62324929 0.74818803 0.78532984]
 [0.86923172 0.92941893 0.96378783]
 [0.51851394 0.44715803 0.23044892]]


In [52]:
print("Abs Value:",np.abs(matrix))
print("Square Root:",np.sqrt(np.abs(matrix)))
print("Square:",np.square(matrix))
print("Cube:",np.cbrt(matrix))

Abs Value: [[1.5 2.3 3.7]
 [4.2 5.6 6.1]
 [7.4 8.5 9.2]
 [3.3 2.8 1.7]]
Square Root: [[1.22474487 1.51657509 1.92353841]
 [2.04939015 2.36643191 2.46981781]
 [2.7202941  2.91547595 3.03315018]
 [1.81659021 1.67332005 1.30384048]]
Square: [[ 2.25  5.29 13.69]
 [17.64 31.36 37.21]
 [54.76 72.25 84.64]
 [10.89  7.84  2.89]]
Cube: [[ 1.14471424 -1.32000612  1.54668037]
 [-1.61342865  1.775808   -1.82716014]
 [ 1.94869516 -2.04082755  2.09537911]
 [-1.48880555  1.40945975 -1.19348319]]


In [53]:
print("Remainder when divided by 3:",np.mod(matrix, 3))
print("Round:",np.round(matrix))
print("Floor:",np.floor(matrix))
print("Ceil:",np.ceil(matrix))


Remainder when divided by 3: [[1.5 0.7 0.7]
 [1.8 2.6 2.9]
 [1.4 0.5 0.2]
 [2.7 2.8 1.3]]

Round: [[ 2. -2.  4.]
 [-4.  6. -6.]
 [ 7. -8.  9.]
 [-3.  3. -2.]]

Floor: [[ 1. -3.  3.]
 [-5.  5. -7.]
 [ 7. -9.  9.]
 [-4.  2. -2.]]

Ceil: [[ 2. -2.  4.]
 [-4.  6. -6.]
 [ 8. -8. 10.]
 [-3.  3. -1.]]


**3. Matrix Statistics and Analysis**

In [54]:
random_matrix= np.random.uniform(-10, 10, (3, 4))
print("Random 3x4 Matrix:",random_matrix)

Random 3x4 Matrix: [[ 1.76381729 -5.45846405  9.52032881  1.04538154]
 [-4.94342007 -5.79609734 -9.67350984  7.67276682]
 [ 9.25437054 -1.88381529 -1.13144855 -4.35240107]]


In [55]:
print("Maximum:", np.max(random_matrix))
print("Minimum:", np.min(random_matrix))
print("Index of Maximum:", np.unravel_index(np.argmax(random_matrix), random_matrix.shape))
print("Index of Minimum:", np.unravel_index(np.argmin(random_matrix), random_matrix.shape))
print("Sum:", np.sum(random_matrix))
print("Product:", np.prod(random_matrix))
print("Mean:", np.mean(random_matrix))
print("Median:", np.median(random_matrix))
print("Variance:", np.var(random_matrix))
print("Standard Deviation:", np.std(random_matrix))

Maximum: 9.520328811183237
Minimum: -9.673509838377603
Index of Maximum: (np.int64(0), np.int64(2))
Index of Minimum: (np.int64(1), np.int64(2))
Sum: -3.9824912239742556
Product: -17494398.322182525
Mean: -0.3318742686645213
Median: -1.5076319220447587
Variance: 36.934139401859525
Standard Deviation: 6.077346411211025
